# Generated by Django 3.2.2 on 2021-10-11 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_category_comment_listing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='listing',
            new_name='title',
        ),
    ]
