# Generated by Django 3.2.2 on 2021-10-11 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_listing_listing_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='select_category', to='auctions.Category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='image_url',
            field=models.URLField(default='google.com'),
        ),
        migrations.AddField(
            model_name='listing',
            name='listing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
        migrations.AddField(
            model_name='listing',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
